namespace MLSApp
{
    internal static class Program
    {
        /// <summary>
        ///  The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            string desc1 = "TRULY MUST SEE to appreciate all the upgrades in this home. Builder upgrades include covered rear patio,garage bump, extended covered front porch, spindle staircase, granite, lighting, and more. Owner upgrades (see attached amenity sheet for SMART FEATURES) include outdoor kitchen/bbq, extended covered/screened patio with remote, fully fenced and landscaped front/back yards w/sprinklers. Entertainers' kitchen, inside and out. RV Parking. So much more.";
            string desc2 = "Come see this rare opportunity for a 5bd/3bath home in airway heights! Only owned by one owner, this seller is offering 10K towards closing costs! In addition, all brand new flooring and interior paint throughout this entire home! New Lenox furnace installed this year, brand new front door entry way, along with new trex deck in both the front and back yard to enjoy your outdoor space! All new kitchen appliances and the W/D stay! Why consider a new build when this home is practically new inside along with a fully fenced yard and sprinkler system already installed with a couple extra bedrooms to enjoy! Don't wait...all this can be yours to entertain friends/family for the upcoming holidays!!";
            string desc3 = "Gorgeous corner lot home with huge curb appeal just minutes from Spokane and Fairchild AFB! Open concept design with blinds installed throughout. Kitchen is completely up to date with black marble counter tops and plenty of cabinet space. Spacious primary bedroom suite with large walk-in closet on the main floor. Fully finished basement with gas insert and huge amounts of storage. Central air conditioning and a three car garage. Three nice sized bedrooms in basement and full bathroom in the basement. Main floor also has an office or formal dining area, and main floor laundry. Fenced backyard and fully landscaped. Keep some money in your pocket versus buying new construction and check out this turn-key home!";
            string desc4 = "Welcome to this wonderfully maintained property ready for you to make your own! Situated on a large fenced lot with beautiful fruit trees and covered patio, you will be at home inside and out. This single level rancher features an open concept layout and high ceilings throughout the kitchen, dining and living areas. This floorplan includes a separate office space in addition to three large bedrooms. The primary suite features a walk-in closet in addition to the ensuite bathroom with dual vanity and large soaker tub. The remaining two bedrooms and bathroom are situated on the opposite side of the home for wonderful separation of space. Ample storage is found in the closets, laundry room, and oversized two car garage. This home is conveniently located next to parks, elementary school, shopping and dining, Spokane International Airport, Fairchild Airforce Base, Northern Quest Resort and Casino, and just 15 minutes from downtown Spokane! All appliances to stay.";
            string desc5 = "To be build two story with 3,354 sq. ft. home. This amazing Rancher style home will offer 3 beds, 2 baths, 2 car garage and unfinished basement. Open floor plan, covered deck. Master suite with walk in closet, double sinks, soaking tub & separate shower. Main floor laundry. Front yard landscape included. No HOA.";
            string desc6 = "Come take a look at this newly renovated move in ready Cape Code home in north Spokane. This home has 3 bedrooms, 2 bathrooms and 3 family rooms. As you walk in you are instantly drawn to the new LVP flooring, new fixtures and fresh paint through out. All brand new, never used kitchen appliances overlooking a step down family room with cathedral ceilings. In the primary suite you will find a new stunning bathroom with walk in tile shower, new fixtures and vanity. Nothing in this home was overlooked. Huge 1200sqft shop with 220v service and built in frame rails. Air compressor and generator included! This shop has it all, fit all your tools and toys with ample parking on site for boats and RV's. Gas heat for cold nights and AC for those hot summer days. Electrical panel and backyard sprinklers were installed in 2020, along with a new heat pump in 2016 and a new water tanks in 2019.You don't want to miss this one!";
            string desc7 = "Welcome to this charming home located in one of the coziest neighborhoods that the South Hill has to offer! Featuring 4 bedrooms, 2 bathrooms, newly updated kitchen with quartz countertops, a gas range, stainless appliances & an island that stretches the entire length of the kitchen! A true entertainer/chef's delight!  Fully egressed basement with outside entry, original hardwoods, 1 car detached garage with additional off-street parking & much more!";
            string desc8 = "Our Cali floor plan is a one level offering 4 bds and 2 baths, spacious Great Room open concept with 9ft ceilings and beautiful and durable laminate floors throughout the common areas (entry, into the kitchen, living room & hallways). The kitchen has a large pantry, spacious island with white quartz countertops and includes stainless steel range, microwave and dishwasher as well as white cabinetry topped with crown molding. The Primary bedroom provides an amazing walk in closet, an oversized shower and dual sinks. The exterior features a covered patio in backyard and easy to maintain SmartSide siding. Spring Air's residents enjoy easy access to the Children of the Sun trail! Photos are file photos, please call listing agent to verify home elevation, interior & exterior color packages.";
            string desc9 = "Nothing to do here but move in to this beautifully remodeled 4 BR/2 BTH home in the coveted Mead School District! All new doors, trim & hardware throughout. All new interior paint. Kitchen has all new white cabinetry, quartz counters, flooring, sink, backsplash, stainless appliances & custom range hood. Main floor bath has all new flooring, tile, sink & lighting. New high-efficiency gas furnace and A/C. Newer carpet and LVP flooring throughout. 2 family rooms and 2 fireplaces. Vinyl windows. Daylight basement has great storage. All appliances stay including front-loading washer and dryer. Oversized park-like yard has a large deck and chicken coop. Circular driveway. Close to 395 and Highway 2 for easy commuting.";
            string desc10 = "Our popular Cambridge floor plan offers a formal dining room with large open concept kitchen and living space. The kitchen features a walk-in pantry, quartz countertops and will include a stainless-steel range, microwave hood, and dishwasher. Upstairs you will find a large primary suite with a walk-in closet, double sink vanity, separate toilet room, and walk in shower. Down the hall there are three additional bedrooms and secondary bath that will include a single sink vanity and tub. This floor plan offers a large bonus room that can be used for a multitude of purposes including, but not limited to an at home movie theater, playroom or home office! the exterior features elegant low maintenance LP Siding.";
            string desc11 = "Amazing one-level living at it's finest! Located in this fantastic maintenance-free gated community! Snow removal from the streets, sidewalks, and driveways, maintenance of common areas, mowing, sprinkler blowouts, all included in the $190 monthly HOA. This home has been extremely well taken care of and recently updated; kitchen, all bathrooms remodeled! Hard surface throughout. Primary has walk-in closet. Garage has extra insulation, attic storage and electric heater. Basement is finished with egress windows. Backyard is somewhat private with covered back patio. You won't be disappointed!";
            string desc12 = "Discover this beautiful 5 bedroom, 3 bathroom mid century home that backs to McDonald Elementary! Large windows bring in plenty of natural light at all levels including skylights upstairs in the primary suite, which also includes double sinks and a large walk in closet! Double living space both upstairs and down, complete with in wall speakers, wall mount, and cables make this space ready for entertaining! 2 bedrooms on upstairs main level and 2 bedrooms down with ample storage throughout. Plenty of closet space, crawl space storage, and a work bench in the garage. Appreciate the new carpet! Step outside onto the oversized deck and into a fully fenced large backyard, perfect for entertaining or unwinding. You'll find a swing, bench, firepit, and playhouse, all included! The raised bed boasts strawberries and a thornless blackberry bush. Don’t miss this opportunity to make all this yours!";
            string desc13 = "Checkout this gorgeous 4 level in the Spokane Valley! The kitchen space is beautiful with custom cabinets and countertops. The eating space was extending to fit a large table and chairs. Lots of space and cabinets! New wood laminate flooring too! Off the kitchen is the formal dining room or formal living room. Several steps down from the kitchen is a large family room with a cozy gas fireplace. A bedroom/den  is also on this floor. The upstairs master is huge with a walk-in closet and a master bath with double sinks. 2 more bedrooms complete the upper floor. Off the family room is the laundry/mudroom and an entry to the fully finished and insulated 3 car garage. A huge covered deck and patio are off the back of the house.... a year round useable space. The huge backyard is fully fenced, has a large shed and a RV parking area with a double gate off the side street. This 2000 year built home sits on a huge corner lot in a cul-da-sac.";
            string desc14 = "Beautifully updated home in Spokane Valley. Don't miss this 4 bed/1 bath home that has been updated but still retains the charm. New paint on the interior as well as exterior. Cozy fireplace looking out on the peaceful neighborhood. All new electrical throughout. New LVP and carpet throughout. Kitchen has updated counters, new stainless steel appliances. Built-ins with lots of storage and large closets. Detached garage, vinyl fenced yard and garden beds with a deck and pleasant backyard. Go see it today.";
            string desc15 = "Spacious corner lot in desirable Indian Trail neighborhood. This home has 4 bedrooms, two family rooms, formal living room, and large dining area. Enjoy your beautiful, oversized back yard from a brand new trex deck (2023). Bedrooms are generously sized. Main bathroom updated in 2015, Furnace/AC/H2O heater new in 2019. This wonderful quiet neighborhood is close to shopping, restaurants, breweries, and park.";
            string desc16 = "Charming three-bedroom, one-bathroom home on the north side is perfect for those seeking a cozy and updated space. This property boasts recent renovations, ensuring a fresh and modern feel throughout. The fully fenced yard provides privacy and security, while the detached garage adds convenience and additional storage space. With a full basement, this home offers versatility for storage, a home office, or even a recreation area. Situated on a bus line, commuting is a breeze, providing easy access to nearby amenities. Enjoy the convenience of being only two minutes away from Trader Joe's, making grocery shopping a quick and simple task. Whether you're a first-time buyer or looking for a low-maintenance residence, this property is a great starter home with nothing left to do but move in and make it your own. Don't miss out on this super cute and welcoming abode!";
            string desc17 = "Nothing to do here but move in to this beautifully remodeled 4 BR/2 BTH home in the coveted Mead School District! All new doors, trim & hardware throughout. All new interior paint. Kitchen has all new white cabinetry, quartz counters, flooring, sink, backsplash, stainless appliances & custom range hood. Main floor bath has all new flooring, tile, sink & lighting. New high-efficiency gas furnace and A/C. Newer carpet and LVP flooring throughout. 2 family rooms and 2 fireplaces. Vinyl windows. Daylight basement has great storage. All appliances stay including front-loading washer and dryer. Oversized park-like yard has a large deck and chicken coop. Circular driveway. Close to 395 and Highway 2 for easy commuting.";
            string desc18 = "The Kerry Plan is a one-story ranch style design with three bedrooms and two baths located in the brand-new community of Spring Air Estates. This 1466 square foot plan includes an elegant entry, as you past through the foyer into the open concept living room and spacious kitchen. Durable laminate wood floors extend throughout most of the home with all bedrooms being carpeted. The kitchen includes stainless steel appliances, Island with quartz countertops. The primary suite boasting a spacious bathroom with walk in closet.";
            string desc19 = "Nestled off of Upriver Drive and located on the quiet street of Shiva Lane sits a beautiful brand-new construction home now ready for you. This nearly 1,800 sq. ft, 4 bed, 3 bath 2 story comes fully-loaded with top of the line appliances, full landscaping, 2-car garage & RV parking! This home was thoughtfully designed by Grit & Timber Properties with the bedrooms and a flex space upstairs and a large living, eating and dining space on the main. Live comfortably and confidently knowing that your home is covered by a 1 year whole-house warranty. Conveniently located within walking distance of Pasadena Park Elementary School, you are a mere 10 minutes away from I-90, grocery, shopping and restaurants. Great location, great product, great value.";
            string desc20 = "Welcome to this fantastic single-level rancher! This home is all about comfort and efficiency. The Great room's open layout allows you to keep your eyes on everything while you cook, making it perfect for everyday life & hosting get-togethers. Breakfast bar, plenty of counter space & large pantry will suit all your needs. The primary bedroom is separate from the others, providing some extra privacy and features two large closets, ¾ bathroom, walk-in shower & the double vanities are a real bonus. Additionally, there are two good-sized bedrooms, one could double as an office or den if you like. The bedrooms share a full bathroom, completing the setup of this smartly designed home. A cozy backyard patio & deck is the perfect spot to enjoy the outdoors relax & bbq. This house is comfortable, functional, and flexible. It's more than just a house; it's a great place to make memories. If you want to see it for yourself, reach out and see it today!";


            Data.HouseList.Add(new House() { MLS = 1, Price = 529000, PriceCat = 8, SqFeet = 2732, SqFeetCat = 6, Bed = 5, Bath = 3, City = City.Spokane, Description = desc1});
            Data.HouseList.Add(new House() { MLS = 2, Price = 429900, PriceCat = 4, SqFeet = 2200, SqFeetCat = 4, Bed = 5, Bath = 3, City = City.AirwayHeights, Description = desc2 });
            Data.HouseList.Add(new House() { MLS = 3, Price = 489000, PriceCat = 6, SqFeet = 3232, SqFeetCat = 8, Bed = 4, Bath = 3, City = City.AirwayHeights, Description = desc3 });
            Data.HouseList.Add(new House() { MLS = 4, Price = 395000, PriceCat = 2, SqFeet = 1706, SqFeetCat = 2, Bed = 3, Bath = 2, City = City.AirwayHeights, Description = desc4 });
            Data.HouseList.Add(new House() { MLS = 5, Price = 460000, PriceCat = 5, SqFeet = 3354, SqFeetCat = 9, Bed = 3, Bath = 2, City = City.AirwayHeights, Description = desc5 });
            Data.HouseList.Add(new House() { MLS = 6, Price = 375000, PriceCat = 2, SqFeet = 2231, SqFeetCat = 4, Bed = 3, Bath = 2, City = City.Spokane, Description = desc6 });
            Data.HouseList.Add(new House() { MLS = 7, Price = 489900, PriceCat = 6, SqFeet = 2094, SqFeetCat = 4, Bed = 4, Bath = 2, City = City.Spokane, Description = desc7 });
            Data.HouseList.Add(new House() { MLS = 8, Price = 451995, PriceCat = 5, SqFeet = 1797, SqFeetCat = 3, Bed = 4, Bath = 2, City = City.Mead, Description = desc8 });
            Data.HouseList.Add(new House() { MLS = 9, Price = 429900, PriceCat = 4, SqFeet = 1932, SqFeetCat = 3, Bed = 4, Bath = 2, City = City.Mead, Description = desc9 });
            Data.HouseList.Add(new House() { MLS = 10, Price = 453995, PriceCat = 5, SqFeet = 2335, SqFeetCat = 5, Bed = 4, Bath = 3, City = City.Mead, Description = desc10 });
            Data.HouseList.Add(new House() { MLS = 11, Price = 490000, PriceCat = 6, SqFeet = 2622, SqFeetCat = 6, Bed = 3, Bath = 3, City = City.SpokaneValley, Description = desc11 });
            Data.HouseList.Add(new House() { MLS = 12, Price = 435000, PriceCat = 4, SqFeet = 2299, SqFeetCat = 5, Bed = 5, Bath = 3, City = City.SpokaneValley, Description = desc12 });
            Data.HouseList.Add(new House() { MLS = 13, Price = 525000, PriceCat = 8, SqFeet = 2542, SqFeetCat = 6, Bed = 5, Bath = 3, City = City.SpokaneValley, Description = desc13 });
            Data.HouseList.Add(new House() { MLS = 14, Price = 369900, PriceCat = 1, SqFeet = 1437, SqFeetCat = 1, Bed = 4, Bath = 1, City = City.SpokaneValley, Description = desc14 });
            Data.HouseList.Add(new House() { MLS = 15, Price = 460000, PriceCat = 5, SqFeet = 2440, SqFeetCat = 5, Bed = 4, Bath = 3, City = City.Spokane, Description = desc15 });
            Data.HouseList.Add(new House() { MLS = 16, Price = 325000, PriceCat = 1, SqFeet = 1452, SqFeetCat = 1, Bed = 3, Bath = 1, City = City.Spokane, Description = desc16 });
            Data.HouseList.Add(new House() { MLS = 17, Price = 419900, PriceCat = 3, SqFeet = 1932, SqFeetCat = 3, Bed = 4, Bath = 2, City = City.Mead, Description = desc17 });
            Data.HouseList.Add(new House() { MLS = 18, Price = 403995, PriceCat = 3, SqFeet = 1466, SqFeetCat = 1, Bed = 3, Bath = 2, City = City.Mead, Description = desc18 });
            Data.HouseList.Add(new House() { MLS = 19, Price = 444950, PriceCat = 4, SqFeet = 1791, SqFeetCat = 3, Bed = 4, Bath = 3, City = City.SpokaneValley, Description = desc19 });
            Data.HouseList.Add(new House() { MLS = 20, Price = 424900, PriceCat = 3, SqFeet = 1412, SqFeetCat = 1, Bed = 3, Bath = 2, City = City.SpokaneValley, Description = desc20 });

            // To customize application configuration such as set high DPI settings or default font,
            // see https://aka.ms/applicationconfiguration.
            ApplicationConfiguration.Initialize();
            Application.Run(new MLSForm());
        }
    }
}